image: Visual Studio 2019

build_script:
  - dotnet publish --configuration Release --framework netcoreapp3.0 --output ./linux --self-contained true --runtime linux-x32
  
artifacts:
  - path: ./linux
