image: Visual Studio 2019 Preview

environment:
  - DOTNET_CLI_TELEMETRY_OPTOUT=1
  
build_script:
  - dotnet publish --configuration Release

artifacts:
  # pushing entire folder as a zip archive
  - path: ./bin/Release/netcoreapp3.0/publish
