name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      with:
        dotnet-version: 3.0.101 
      uses: actions/setup-dotnet@v1
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - uses: juankaram/archive-action@v1.0.0
      name: Create tar archive
      with:
        args: tar -cfvf ./build.tar.gz ./bin/Release/netcoreapp3.0/
    - name: Release build artifacts
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        dotnet-version: 3.0.101 
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Auto Build"
        files: |
          ./build.tar.gz
    
